# port is the port number for the web server, where listens for incoming requests
# api_base_url is the base URL for the API Gateway, where the web server will send requests
#   -> the port should match the one used in the API Gateway service
#   -> the URL should point to the API Gateway service in your Docker network

api_gateway:
  # Local development
  base_url: "http://localhost:8080"
global_temperature:
  host: "0.0.0.0"
  port: 8100