name: composed-mqtt-project

services:

  ### MQTT Broker Service
  broker:
    image: eclipse-mosquitto:2.0.21
    container_name: my-mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    networks:
      - mqtt-net


  ### Example services for sending and receiving MQTT messages
  ###   Look mqtt-tester for more details
  #
  # sender:
  #   build:
  #     context: ./docker_send
  #     dockerfile: Dockerfile
  #   container_name: mqtt_sender
  #   depends_on:
  #     - broker
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   networks:
  #     - mqtt-net
  #
  # receiver:
  #   build:
  #     context: ./docker_recv
  #     dockerfile: Dockerfile
  #   container_name: mqtt_receiver
  #   depends_on:
  #     - broker
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   networks:
  #     - mqtt-net
  #

networks:
  mqtt-net:
    driver: bridge