name: composed-mqtt-project

## ALL PORTS are decided by flowchart/port_flowchart.mmd
# The ip address is the service name, e.g., `broker` for the MQTT broker, `web-ui` for the web UI

services:

  ### MQTT Broker Service
  broker:
    image: eclipse-mosquitto:2.0.21
    container_name: my-mosquitto-broker-container
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    networks:
      - iot_network

  ### Web UI Service
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: web-ui-container
    ports:
      - "8000:8000"
    volumes:
      - ./web-ui/target_web_conf.yaml:/app/web_conf.yaml
    networks:
      - iot_network
    restart: always
    #depends_on:
    #  - api-gateway

networks:
  iot_network:
    driver: bridge