# Priority Queue Manager Configuration

server:
  host: '0.0.0.0'
  port: 8090
  debug: true

logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/priority-queue-manager.log'
  max_size: 10485760  # 10MB
  backup_count: 5

service:
  name: 'priority-queue-manager'
  version: '1.0.0'