flowchart TB

ST --> PrinterMon

APIGW o--o|HTTP| TempGlobal

TempSensor --> TempGlobal
TempSensor --> Anomaly

GUI["🧑‍💻 User Interface (GUI)"]
Robot["🤖 ROB Robot"]
Fan["💨 Fan Unit"]
PrinterMon["🖨 Printer Monitoring"]
ST["🧱 ST Printer"]
APIGW["🛰 API Gateway"]
QueueMgr["📋 Priority Queue Manager"]
TempGlobal["🌡 Global Temperature"]
JobHandler["🧠 Job Handler"]
Planning["🧭 Robot Management"]
Anomaly["⚠️ Anomaly Detection"]
FanCtrl["🌀 Fan Controller"]
TempSensor["🌡 Room Temp Sensor"]

ST --> TempGlobal
ST --> Anomaly

TempGlobal --> FanCtrl
Anomaly --> FanCtrl
FanCtrl --> Fan
 
GUI o--o|HTTP| APIGW
APIGW o--o|HTTP| QueueMgr
APIGW o--o|HTTP| PrinterMon
QueueMgr o--o|HTTP| JobHandler

JobHandler <--> Planning
Planning <--> Robot
Robot --> JobHandler

JobHandler --> ST