flowchart TB

ST -->|MQTT:
device/printer/-ID-/progress| PrinterMon

APIGW o--o|HTTP:
 get| TempGlobal

TempSensor -->|MQTT:
device/room/temperature| TempGlobal
TempSensor -->|MQTT:
device/room/temperature| Anomaly

GUI["🧑‍💻 User Interface (GUI)"]
Robot["🤖 ROB Robot"]
Fan["💨 Fan Unit"]
PrinterMon["🖨 Printer Monitoring"]
ST["🧱 ST Printer"]
APIGW["🛰 API Gateway"]
QueueMgr["📋 Priority Queue Manager"]
TempGlobal["🌡 Global Temperature"]
JobHandler["🧠 Job Handler"]
Planning["🧭 Robot Management"]
Anomaly["⚠️ Anomaly Detection"]
FanCtrl["🌀 Fan Controller"]
TempSensor["🌡 Room Temp Sensor"]

ST -->|MQTT:
device/printer/-ID-/temperature| TempGlobal
ST -->|MQTT:
device/printer/-ID-/temperature| Anomaly

TempGlobal -->|MQTT:
device/fan/controller/status| FanCtrl
Anomaly -->|MQTT:
device/fan/controller/emergency| FanCtrl
FanCtrl -->|MQTT:
device/fan/-ID-/speed| Fan

GUI o--o|HTTP| APIGW
APIGW o--o|HTTP:
get, post, delete, put| QueueMgr
APIGW o--o|HTTP:
get| PrinterMon
QueueMgr o--o|HTTP:
get, delete| JobHandler

JobHandler -->|MQTT:
device/printers| Planning
Planning <-->|MQTT:
device/robot/-ID-/coordinates
device/robot/-ID-/progress| Robot
Robot -->|MQTT:
device/robot/-ID-/progress| JobHandler

JobHandler -->|MQTT:
device/printer/-ID-/assignement| ST