web:
  host: "host.docker.internal"
  port: 8090
  debug: true

persistence:
  file_path: "data/queue_data.json"
  backup_interval: 300  # seconds

logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

integration:
  job_handler_url: "http://host.docker.internal:8081"
  web_ui_url: "http://host.docker.internal:8000"